/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef ADDITIONALMMCONTEXTFORSRVCCIE_H_
#define ADDITIONALMMCONTEXTFORSRVCCIE_H_

#include "manual/gtpV2Ie.h"



class AdditionalMmContextForSrvccIe: public GtpV2Ie {
public:
    AdditionalMmContextForSrvccIe();
    virtual ~AdditionalMmContextForSrvccIe();

    bool encodeAdditionalMmContextForSrvccIe(MsgBuffer &buffer,
                 AdditionalMmContextForSrvccIeData const &data);
    bool decodeAdditionalMmContextForSrvccIe(MsgBuffer &buffer,
                 AdditionalMmContextForSrvccIeData &data, Uint16 length);
    void displayAdditionalMmContextForSrvccIe_v(AdditionalMmContextForSrvccIeData const &data,
                 Debug &stream);
};

#endif /* ADDITIONALMMCONTEXTFORSRVCCIE_H_ */
