/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.cpp.tt>
 ******************************************************************************/

#include "additionalFlagsForSrvccIe.h"
#include "dataTypeCodecUtils.h"

AdditionalFlagsForSrvccIe::AdditionalFlagsForSrvccIe() 
{
    ieType = 160;
    // TODO

}

AdditionalFlagsForSrvccIe::~AdditionalFlagsForSrvccIe() {
    // TODO Auto-generated destructor stub
}

bool AdditionalFlagsForSrvccIe::encodeAdditionalFlagsForSrvccIe(MsgBuffer &buffer, AdditionalFlagsForSrvccIeData const &data)
{
    buffer.skipBits(6);

    if(!(buffer.writeBits(data.vf, 1)))
    {
        errorStream.add((char *)"Encoding of vf failed\n");
        return false;
    }
    if(!(buffer.writeBits(data.ics, 1)))
    {
        errorStream.add((char *)"Encoding of ics failed\n");
        return false;
    }

    return true;
}

bool AdditionalFlagsForSrvccIe::decodeAdditionalFlagsForSrvccIe(MsgBuffer &buffer, AdditionalFlagsForSrvccIeData &data, Uint16 length)
{     
    // TODO optimize the length checks
    
    Uint16 ieBoundary = buffer.getCurrentIndex() + length;
    buffer.skipBits(6);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: \n");
        return false;
    }

    data.vf = buffer.readBits(1);
    // confirm that we are not reading beyond the IE boundary
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: vf\n");
        return false;
    }
    data.ics = buffer.readBits(1);
    // confirm that we are not reading beyond the IE boundary
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: ics\n");
        return false;
    }

    // The IE is decoded now. The buffer index should be pointing to the 
    // IE Boundary. If not, we have some more data left for the IE which we don't know
    // how to decode
    if (ieBoundary == buffer.getCurrentIndex())
    {
        return true;
    }
    else
    {
        errorStream.add((char *)"Unable to decode IE AdditionalFlagsForSrvccIe\n");
        return false;
    }
}
void AdditionalFlagsForSrvccIe::displayAdditionalFlagsForSrvccIe_v(AdditionalFlagsForSrvccIeData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"AdditionalFlagsForSrvccIeData:");
    stream.incrIndent();
    stream.endOfLine();
  
    stream.add( (char *)"vf: "); 
    stream.add((Uint8)data.vf);
    stream.endOfLine();
  
    stream.add( (char *)"ics: "); 
    stream.add((Uint8)data.ics);
    stream.endOfLine();
    stream.decrIndent();
    stream.decrIndent();
}
