/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */ 

/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/grpieinsttemplate.cpp.tt>
 ******************************************************************************/
 
#include "bearerContextsInForwardRelocationRequest.h"
#include "manual/gtpV2Ie.h"
#include "gtpV2IeFactory.h"
#include "ebiIe.h"
#include "bearerTftIe.h"
#include "fTeidIe.h"
#include "fTeidIe.h"
#include "bearerQosIe.h"
#include "fContainerIe.h"
#include "tiIe.h"
#include "bearerFlagsIe.h"
#include "fTeidIe.h"

BearerContextsInForwardRelocationRequest::
BearerContextsInForwardRelocationRequest()
{
    Uint16 mandIe;
    mandIe = EbiIeType;
    mandIe = (mandIe << 8) | 0; // epsBearerId
    mandatoryIeSet.insert(mandIe);
    mandIe = FTeidIeType;
    mandIe = (mandIe << 8) | 0; // sgwS1S4S12IpAddressAndTeidForUserPlane
    mandatoryIeSet.insert(mandIe);
    mandIe = BearerQosIeType;
    mandIe = (mandIe << 8) | 0; // bearerLevelQos
    mandatoryIeSet.insert(mandIe);

}

BearerContextsInForwardRelocationRequest::
~BearerContextsInForwardRelocationRequest()
{

}
bool BearerContextsInForwardRelocationRequest::
encodeBearerContextsInForwardRelocationRequest(MsgBuffer &buffer,
                         BearerContextsInForwardRelocationRequestData
                          const &data)
{
    bool rc = false;
    GtpV2IeHeader header;
    Uint16 startIndex = 0;
    Uint16 endIndex = 0;
    Uint16 length = 0;


    
    // Encode the Ie Header
    header.ieType = EbiIeType;
    header.instance = 0;
    header.length = 0; // We will encode the IE first and then update the length
    GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
    startIndex = buffer.getCurrentIndex(); 
    EbiIe epsBearerId=
    dynamic_cast<
    EbiIe&>(GtpV2IeFactory::getInstance().getIeObject(EbiIeType));
    rc = epsBearerId.encodeEbiIe(buffer, data.epsBearerId);
    endIndex = buffer.getCurrentIndex();
    length = endIndex - startIndex;
    
    // encode the length value now
    buffer.goToIndex(startIndex - 3);
    buffer.writeUint16(length, false);
    buffer.goToIndex(endIndex);
    if (!(rc))
    {
        errorStream.add((char *)"Failed to encode IE: epsBearerId\n");
        return false;
    }
    if (data.tftIePresent)
    {
        
        // Encode the Ie Header
        header.ieType = BearerTftIeType;
        header.instance = 0;
        header.length = 0; // We will encode the IE first and then update the length
        GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
        startIndex = buffer.getCurrentIndex(); 
        BearerTftIe tft=
        dynamic_cast<
        BearerTftIe&>(GtpV2IeFactory::getInstance().getIeObject(BearerTftIeType));
        rc = tft.encodeBearerTftIe(buffer, data.tft);
        endIndex = buffer.getCurrentIndex();
        length = endIndex - startIndex;
        
        // encode the length value now
        buffer.goToIndex(startIndex - 3);
        buffer.writeUint16(length, false);
        buffer.goToIndex(endIndex);

        if (!(rc))
        {
          errorStream.add((char *)"Failed to encode IE: tft\n");
          return false;
        }
    }

    
    // Encode the Ie Header
    header.ieType = FTeidIeType;
    header.instance = 0;
    header.length = 0; // We will encode the IE first and then update the length
    GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
    startIndex = buffer.getCurrentIndex(); 
    FTeidIe sgwS1S4S12IpAddressAndTeidForUserPlane=
    dynamic_cast<
    FTeidIe&>(GtpV2IeFactory::getInstance().getIeObject(FTeidIeType));
    rc = sgwS1S4S12IpAddressAndTeidForUserPlane.encodeFTeidIe(buffer, data.sgwS1S4S12IpAddressAndTeidForUserPlane);
    endIndex = buffer.getCurrentIndex();
    length = endIndex - startIndex;
    
    // encode the length value now
    buffer.goToIndex(startIndex - 3);
    buffer.writeUint16(length, false);
    buffer.goToIndex(endIndex);
    if (!(rc))
    {
        errorStream.add((char *)"Failed to encode IE: sgwS1S4S12IpAddressAndTeidForUserPlane\n");
        return false;
    }
    if (data.pgwS5S8IpAddressAndTeidForUserPlaneIePresent)
    {
        
        // Encode the Ie Header
        header.ieType = FTeidIeType;
        header.instance = 1;
        header.length = 0; // We will encode the IE first and then update the length
        GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
        startIndex = buffer.getCurrentIndex(); 
        FTeidIe pgwS5S8IpAddressAndTeidForUserPlane=
        dynamic_cast<
        FTeidIe&>(GtpV2IeFactory::getInstance().getIeObject(FTeidIeType));
        rc = pgwS5S8IpAddressAndTeidForUserPlane.encodeFTeidIe(buffer, data.pgwS5S8IpAddressAndTeidForUserPlane);
        endIndex = buffer.getCurrentIndex();
        length = endIndex - startIndex;
        
        // encode the length value now
        buffer.goToIndex(startIndex - 3);
        buffer.writeUint16(length, false);
        buffer.goToIndex(endIndex);

        if (!(rc))
        {
          errorStream.add((char *)"Failed to encode IE: pgwS5S8IpAddressAndTeidForUserPlane\n");
          return false;
        }
    }

    
    // Encode the Ie Header
    header.ieType = BearerQosIeType;
    header.instance = 0;
    header.length = 0; // We will encode the IE first and then update the length
    GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
    startIndex = buffer.getCurrentIndex(); 
    BearerQosIe bearerLevelQos=
    dynamic_cast<
    BearerQosIe&>(GtpV2IeFactory::getInstance().getIeObject(BearerQosIeType));
    rc = bearerLevelQos.encodeBearerQosIe(buffer, data.bearerLevelQos);
    endIndex = buffer.getCurrentIndex();
    length = endIndex - startIndex;
    
    // encode the length value now
    buffer.goToIndex(startIndex - 3);
    buffer.writeUint16(length, false);
    buffer.goToIndex(endIndex);
    if (!(rc))
    {
        errorStream.add((char *)"Failed to encode IE: bearerLevelQos\n");
        return false;
    }
    if (data.bssContainerIePresent)
    {
        
        // Encode the Ie Header
        header.ieType = FContainerIeType;
        header.instance = 0;
        header.length = 0; // We will encode the IE first and then update the length
        GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
        startIndex = buffer.getCurrentIndex(); 
        FContainerIe bssContainer=
        dynamic_cast<
        FContainerIe&>(GtpV2IeFactory::getInstance().getIeObject(FContainerIeType));
        rc = bssContainer.encodeFContainerIe(buffer, data.bssContainer);
        endIndex = buffer.getCurrentIndex();
        length = endIndex - startIndex;
        
        // encode the length value now
        buffer.goToIndex(startIndex - 3);
        buffer.writeUint16(length, false);
        buffer.goToIndex(endIndex);

        if (!(rc))
        {
          errorStream.add((char *)"Failed to encode IE: bssContainer\n");
          return false;
        }
    }
    if (data.transactionIdentifierIePresent)
    {
        
        // Encode the Ie Header
        header.ieType = TiIeType;
        header.instance = 0;
        header.length = 0; // We will encode the IE first and then update the length
        GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
        startIndex = buffer.getCurrentIndex(); 
        TiIe transactionIdentifier=
        dynamic_cast<
        TiIe&>(GtpV2IeFactory::getInstance().getIeObject(TiIeType));
        rc = transactionIdentifier.encodeTiIe(buffer, data.transactionIdentifier);
        endIndex = buffer.getCurrentIndex();
        length = endIndex - startIndex;
        
        // encode the length value now
        buffer.goToIndex(startIndex - 3);
        buffer.writeUint16(length, false);
        buffer.goToIndex(endIndex);

        if (!(rc))
        {
          errorStream.add((char *)"Failed to encode IE: transactionIdentifier\n");
          return false;
        }
    }
    if (data.bearerFlagsIePresent)
    {
        
        // Encode the Ie Header
        header.ieType = BearerFlagsIeType;
        header.instance = 0;
        header.length = 0; // We will encode the IE first and then update the length
        GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
        startIndex = buffer.getCurrentIndex(); 
        BearerFlagsIe bearerFlags=
        dynamic_cast<
        BearerFlagsIe&>(GtpV2IeFactory::getInstance().getIeObject(BearerFlagsIeType));
        rc = bearerFlags.encodeBearerFlagsIe(buffer, data.bearerFlags);
        endIndex = buffer.getCurrentIndex();
        length = endIndex - startIndex;
        
        // encode the length value now
        buffer.goToIndex(startIndex - 3);
        buffer.writeUint16(length, false);
        buffer.goToIndex(endIndex);

        if (!(rc))
        {
          errorStream.add((char *)"Failed to encode IE: bearerFlags\n");
          return false;
        }
    }
    if (data.sgwS11IpAddressAndTeidForUserPlaneIePresent)
    {
        
        // Encode the Ie Header
        header.ieType = FTeidIeType;
        header.instance = 2;
        header.length = 0; // We will encode the IE first and then update the length
        GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
        startIndex = buffer.getCurrentIndex(); 
        FTeidIe sgwS11IpAddressAndTeidForUserPlane=
        dynamic_cast<
        FTeidIe&>(GtpV2IeFactory::getInstance().getIeObject(FTeidIeType));
        rc = sgwS11IpAddressAndTeidForUserPlane.encodeFTeidIe(buffer, data.sgwS11IpAddressAndTeidForUserPlane);
        endIndex = buffer.getCurrentIndex();
        length = endIndex - startIndex;
        
        // encode the length value now
        buffer.goToIndex(startIndex - 3);
        buffer.writeUint16(length, false);
        buffer.goToIndex(endIndex);

        if (!(rc))
        {
          errorStream.add((char *)"Failed to encode IE: sgwS11IpAddressAndTeidForUserPlane\n");
          return false;
        }
    }
    return rc;
}

bool BearerContextsInForwardRelocationRequest::
decodeBearerContextsInForwardRelocationRequest(MsgBuffer &buffer,
                         BearerContextsInForwardRelocationRequestData 
                         &data, Uint16 length)
{
    Uint16 groupedIeBoundary = length + buffer.getCurrentIndex();
    bool rc = false;
    GtpV2IeHeader ieHeader;
    set<Uint16> mandatoryIeLocalList = mandatoryIeSet;
    while ((buffer.lengthLeft() > IE_HEADER_SIZE) &&
                   (buffer.getCurrentIndex() < groupedIeBoundary))
    {
        GtpV2Ie::decodeGtpV2IeHeader(buffer, ieHeader);
        if (ieHeader.length > buffer.lengthLeft())
        {
            // We do not have enough bytes left in the message for this IE
            errorStream.add((char *)"IE Length exceeds beyond message boundary\n");
            errorStream.add((char *)"  Offending IE Type: ");
            errorStream.add(ieHeader.ieType);
            errorStream.add((char *)"\n  Ie Length in Header: ");
            errorStream.add(ieHeader.length);
            errorStream.add((char *)"\n  Bytes left in message: ");
            errorStream.add(buffer.lengthLeft());
            errorStream.endOfLine();
            return false;
        }
    
        switch (ieHeader.ieType){
            case EbiIeType:
            {
                EbiIe ieObject =
                dynamic_cast<
                EbiIe&>(GtpV2IeFactory::getInstance().
                         getIeObject(EbiIeType));

                if(ieHeader.instance == 0)
                {

                    rc = ieObject.decodeEbiIe(buffer, data.epsBearerId, ieHeader.length);

                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: epsBearerId\n");
                        return false;
                    }
                    Uint16 mandIe = EbiIeType;
                    mandIe = (mandIe << 8) | 0;
                    mandatoryIeLocalList.erase(mandIe);
                }
                else
                {
                    // Unknown IE instance print error TODO
                    errorStream.add((char *)"Unknown IE Type: ");
                    errorStream.add(ieHeader.ieType);
                    errorStream.endOfLine();
                    buffer.skipBytes(ieHeader.length);
                }
                break;
            }
            case BearerTftIeType:
            {
                BearerTftIe ieObject =
                dynamic_cast<
                BearerTftIe&>(GtpV2IeFactory::getInstance().
                         getIeObject(BearerTftIeType));

                if(ieHeader.instance == 0)
                {

                    rc = ieObject.decodeBearerTftIe(buffer, data.tft, ieHeader.length);

                    data.tftIePresent = true;
                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: tft\n");
                        return false;
                    }
                }
                else
                {
                    // Unknown IE instance print error TODO
                    errorStream.add((char *)"Unknown IE Type: ");
                    errorStream.add(ieHeader.ieType);
                    errorStream.endOfLine();
                    buffer.skipBytes(ieHeader.length);
                }
                break;
            }
            case FTeidIeType:
            {
                FTeidIe ieObject =
                dynamic_cast<
                FTeidIe&>(GtpV2IeFactory::getInstance().
                         getIeObject(FTeidIeType));

                if(ieHeader.instance == 0)
                {

                    rc = ieObject.decodeFTeidIe(buffer, data.sgwS1S4S12IpAddressAndTeidForUserPlane, ieHeader.length);

                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: sgwS1S4S12IpAddressAndTeidForUserPlane\n");
                        return false;
                    }
                    Uint16 mandIe = FTeidIeType;
                    mandIe = (mandIe << 8) | 0;
                    mandatoryIeLocalList.erase(mandIe);
                }
                else if(ieHeader.instance == 1)
                {

                    rc = ieObject.decodeFTeidIe(buffer, data.pgwS5S8IpAddressAndTeidForUserPlane, ieHeader.length);

                    data.pgwS5S8IpAddressAndTeidForUserPlaneIePresent = true;
                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: pgwS5S8IpAddressAndTeidForUserPlane\n");
                        return false;
                    }
                }
                else if(ieHeader.instance == 2)
                {

                    rc = ieObject.decodeFTeidIe(buffer, data.sgwS11IpAddressAndTeidForUserPlane, ieHeader.length);

                    data.sgwS11IpAddressAndTeidForUserPlaneIePresent = true;
                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: sgwS11IpAddressAndTeidForUserPlane\n");
                        return false;
                    }
                }
                else
                {
                    // Unknown IE instance print error TODO
                    errorStream.add((char *)"Unknown IE Type: ");
                    errorStream.add(ieHeader.ieType);
                    errorStream.endOfLine();
                    buffer.skipBytes(ieHeader.length);
                }
                break;
            }
            case BearerQosIeType:
            {
                BearerQosIe ieObject =
                dynamic_cast<
                BearerQosIe&>(GtpV2IeFactory::getInstance().
                         getIeObject(BearerQosIeType));

                if(ieHeader.instance == 0)
                {

                    rc = ieObject.decodeBearerQosIe(buffer, data.bearerLevelQos, ieHeader.length);

                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: bearerLevelQos\n");
                        return false;
                    }
                    Uint16 mandIe = BearerQosIeType;
                    mandIe = (mandIe << 8) | 0;
                    mandatoryIeLocalList.erase(mandIe);
                }
                else
                {
                    // Unknown IE instance print error TODO
                    errorStream.add((char *)"Unknown IE Type: ");
                    errorStream.add(ieHeader.ieType);
                    errorStream.endOfLine();
                    buffer.skipBytes(ieHeader.length);
                }
                break;
            }
            case FContainerIeType:
            {
                FContainerIe ieObject =
                dynamic_cast<
                FContainerIe&>(GtpV2IeFactory::getInstance().
                         getIeObject(FContainerIeType));

                if(ieHeader.instance == 0)
                {

                    rc = ieObject.decodeFContainerIe(buffer, data.bssContainer, ieHeader.length);

                    data.bssContainerIePresent = true;
                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: bssContainer\n");
                        return false;
                    }
                }
                else
                {
                    // Unknown IE instance print error TODO
                    errorStream.add((char *)"Unknown IE Type: ");
                    errorStream.add(ieHeader.ieType);
                    errorStream.endOfLine();
                    buffer.skipBytes(ieHeader.length);
                }
                break;
            }
            case TiIeType:
            {
                TiIe ieObject =
                dynamic_cast<
                TiIe&>(GtpV2IeFactory::getInstance().
                         getIeObject(TiIeType));

                if(ieHeader.instance == 0)
                {

                    rc = ieObject.decodeTiIe(buffer, data.transactionIdentifier, ieHeader.length);

                    data.transactionIdentifierIePresent = true;
                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: transactionIdentifier\n");
                        return false;
                    }
                }
                else
                {
                    // Unknown IE instance print error TODO
                    errorStream.add((char *)"Unknown IE Type: ");
                    errorStream.add(ieHeader.ieType);
                    errorStream.endOfLine();
                    buffer.skipBytes(ieHeader.length);
                }
                break;
            }
            case BearerFlagsIeType:
            {
                BearerFlagsIe ieObject =
                dynamic_cast<
                BearerFlagsIe&>(GtpV2IeFactory::getInstance().
                         getIeObject(BearerFlagsIeType));

                if(ieHeader.instance == 0)
                {

                    rc = ieObject.decodeBearerFlagsIe(buffer, data.bearerFlags, ieHeader.length);

                    data.bearerFlagsIePresent = true;
                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: bearerFlags\n");
                        return false;
                    }
                }
                else
                {
                    // Unknown IE instance print error TODO
                    errorStream.add((char *)"Unknown IE Type: ");
                    errorStream.add(ieHeader.ieType);
                    errorStream.endOfLine();
                    buffer.skipBytes(ieHeader.length);
                }
                break;
            }
            default:
            {
            // Unknown IE print error
            errorStream.add((char *)"Unknown IE Type: ");
            errorStream.add(ieHeader.ieType);
            errorStream.endOfLine();
            buffer.skipBytes(ieHeader.length);
            }
        }
    }
    if (!mandatoryIeLocalList.empty())
    {
        // some mandatory IEs are missing
        errorStream.add((char *)"Missing Mandatory IEs:");
        errorStream.endOfLine();
        while (!mandatoryIeLocalList.empty())
        {
            Uint16 missingMandIe = *mandatoryIeLocalList.begin ();
            mandatoryIeLocalList.erase (mandatoryIeLocalList.begin ());
            Uint16 missingInstance = missingMandIe & 0x00FF;
            Uint16 missingIeType = (missingMandIe >> 8);
            errorStream.add ((char *)"Missing Ie type: ");
            errorStream.add (missingIeType);
            errorStream.add ((char *)"  Instance: ");
            errorStream.add (missingInstance);
            errorStream.endOfLine();
        }
        rc = false;
    
    }
    return rc; 
}

void BearerContextsInForwardRelocationRequest::
displayBearerContextsInForwardRelocationRequestData_v
(BearerContextsInForwardRelocationRequestData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"BearerContextsInForwardRelocationRequest:");
    stream.endOfLine();
    stream.incrIndent();

    stream.add((char *)"epsBearerId:");
    stream.endOfLine();
    EbiIe epsBearerId=
    dynamic_cast<
    EbiIe&>(GtpV2IeFactory::getInstance().getIeObject(EbiIeType));
    epsBearerId.displayEbiIe_v(data.epsBearerId, stream);

    if (data.tftIePresent)
    {
        stream.add((char *)"tft:");
        stream.endOfLine();
        BearerTftIe tft=
        dynamic_cast<
        BearerTftIe&>(GtpV2IeFactory::getInstance().getIeObject(BearerTftIeType));
        tft.displayBearerTftIe_v(data.tft, stream);

	}
     stream.add((char *)"sgwS1S4S12IpAddressAndTeidForUserPlane:");
    stream.endOfLine();
    FTeidIe sgwS1S4S12IpAddressAndTeidForUserPlane=
    dynamic_cast<
    FTeidIe&>(GtpV2IeFactory::getInstance().getIeObject(FTeidIeType));
    sgwS1S4S12IpAddressAndTeidForUserPlane.displayFTeidIe_v(data.sgwS1S4S12IpAddressAndTeidForUserPlane, stream);

    if (data.pgwS5S8IpAddressAndTeidForUserPlaneIePresent)
    {
        stream.add((char *)"pgwS5S8IpAddressAndTeidForUserPlane:");
        stream.endOfLine();
        FTeidIe pgwS5S8IpAddressAndTeidForUserPlane=
        dynamic_cast<
        FTeidIe&>(GtpV2IeFactory::getInstance().getIeObject(FTeidIeType));
        pgwS5S8IpAddressAndTeidForUserPlane.displayFTeidIe_v(data.pgwS5S8IpAddressAndTeidForUserPlane, stream);

	}
     stream.add((char *)"bearerLevelQos:");
    stream.endOfLine();
    BearerQosIe bearerLevelQos=
    dynamic_cast<
    BearerQosIe&>(GtpV2IeFactory::getInstance().getIeObject(BearerQosIeType));
    bearerLevelQos.displayBearerQosIe_v(data.bearerLevelQos, stream);

    if (data.bssContainerIePresent)
    {
        stream.add((char *)"bssContainer:");
        stream.endOfLine();
        FContainerIe bssContainer=
        dynamic_cast<
        FContainerIe&>(GtpV2IeFactory::getInstance().getIeObject(FContainerIeType));
        bssContainer.displayFContainerIe_v(data.bssContainer, stream);

	}
     if (data.transactionIdentifierIePresent)
    {
        stream.add((char *)"transactionIdentifier:");
        stream.endOfLine();
        TiIe transactionIdentifier=
        dynamic_cast<
        TiIe&>(GtpV2IeFactory::getInstance().getIeObject(TiIeType));
        transactionIdentifier.displayTiIe_v(data.transactionIdentifier, stream);

	}
     if (data.bearerFlagsIePresent)
    {
        stream.add((char *)"bearerFlags:");
        stream.endOfLine();
        BearerFlagsIe bearerFlags=
        dynamic_cast<
        BearerFlagsIe&>(GtpV2IeFactory::getInstance().getIeObject(BearerFlagsIeType));
        bearerFlags.displayBearerFlagsIe_v(data.bearerFlags, stream);

	}
     if (data.sgwS11IpAddressAndTeidForUserPlaneIePresent)
    {
        stream.add((char *)"sgwS11IpAddressAndTeidForUserPlane:");
        stream.endOfLine();
        FTeidIe sgwS11IpAddressAndTeidForUserPlane=
        dynamic_cast<
        FTeidIe&>(GtpV2IeFactory::getInstance().getIeObject(FTeidIeType));
        sgwS11IpAddressAndTeidForUserPlane.displayFTeidIe_v(data.sgwS11IpAddressAndTeidForUserPlane, stream);

	}
 
    stream.decrIndent();
    stream.decrIndent();
}



