/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef CMIIE_H_
#define CMIIE_H_

#include "manual/gtpV2Ie.h"



class CmiIe: public GtpV2Ie {
public:
    CmiIe();
    virtual ~CmiIe();

    bool encodeCmiIe(MsgBuffer &buffer,
                 CmiIeData const &data);
    bool decodeCmiIe(MsgBuffer &buffer,
                 CmiIeData &data, Uint16 length);
    void displayCmiIe_v(CmiIeData const &data,
                 Debug &stream);
};

#endif /* CMIIE_H_ */
