/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef CSGIDIE_H_
#define CSGIDIE_H_

#include "manual/gtpV2Ie.h"



class CsgIdIe: public GtpV2Ie {
public:
    CsgIdIe();
    virtual ~CsgIdIe();

    bool encodeCsgIdIe(MsgBuffer &buffer,
                 CsgIdIeData const &data);
    bool decodeCsgIdIe(MsgBuffer &buffer,
                 CsgIdIeData &data, Uint16 length);
    void displayCsgIdIe_v(CsgIdIeData const &data,
                 Debug &stream);
};

#endif /* CSGIDIE_H_ */
