/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef FCAUSEIE_H_
#define FCAUSEIE_H_

#include "manual/gtpV2Ie.h"



class FCauseIe: public GtpV2Ie {
public:
    FCauseIe();
    virtual ~FCauseIe();

    bool encodeFCauseIe(MsgBuffer &buffer,
                 FCauseIeData const &data);
    bool decodeFCauseIe(MsgBuffer &buffer,
                 FCauseIeData &data, Uint16 length);
    void displayFCauseIe_v(FCauseIeData const &data,
                 Debug &stream);
};

#endif /* FCAUSEIE_H_ */
