/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.cpp.tt>
 ******************************************************************************/

#include "headerCompressionConfigurationIe.h"
#include "dataTypeCodecUtils.h"

HeaderCompressionConfigurationIe::HeaderCompressionConfigurationIe() 
{
    ieType = 196;
    // TODO

}

HeaderCompressionConfigurationIe::~HeaderCompressionConfigurationIe() {
    // TODO Auto-generated destructor stub
}

bool HeaderCompressionConfigurationIe::encodeHeaderCompressionConfigurationIe(MsgBuffer &buffer, HeaderCompressionConfigurationIeData const &data)
{
    if (!(buffer.writeUint16(data.rohcProfiles)))
    {
        errorStream.add((char *)"Encoding of rohcProfiles failed\n");
        return false;
    }
    if (!(buffer.writeUint16(data.maxCid)))
    {
        errorStream.add((char *)"Encoding of maxCid failed\n");
        return false;
    }

    return true;
}

bool HeaderCompressionConfigurationIe::decodeHeaderCompressionConfigurationIe(MsgBuffer &buffer, HeaderCompressionConfigurationIeData &data, Uint16 length)
{     
    // TODO optimize the length checks
    
    Uint16 ieBoundary = buffer.getCurrentIndex() + length;

    buffer.readUint16(data.rohcProfiles);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: rohcProfiles\n");
        return false;
    }

    buffer.readUint16(data.maxCid);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: maxCid\n");
        return false;
    }

    // The IE is decoded now. The buffer index should be pointing to the 
    // IE Boundary. If not, we have some more data left for the IE which we don't know
    // how to decode
    if (ieBoundary == buffer.getCurrentIndex())
    {
        return true;
    }
    else
    {
        errorStream.add((char *)"Unable to decode IE HeaderCompressionConfigurationIe\n");
        return false;
    }
}
void HeaderCompressionConfigurationIe::displayHeaderCompressionConfigurationIe_v(HeaderCompressionConfigurationIeData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"HeaderCompressionConfigurationIeData:");
    stream.incrIndent();
    stream.endOfLine();
  
    stream.add((char *)"rohcProfiles: ");
    stream.add(data.rohcProfiles);
    stream.endOfLine();
  
    stream.add((char *)"maxCid: ");
    stream.add(data.maxCid);
    stream.endOfLine();
    stream.decrIndent();
    stream.decrIndent();
}
