/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.cpp.tt>
 ******************************************************************************/

#include "monitoringEventInformationIe.h"
#include "dataTypeCodecUtils.h"

MonitoringEventInformationIe::MonitoringEventInformationIe() 
{
    ieType = 189;
    // TODO

}

MonitoringEventInformationIe::~MonitoringEventInformationIe() {
    // TODO Auto-generated destructor stub
}

bool MonitoringEventInformationIe::encodeMonitoringEventInformationIe(MsgBuffer &buffer, MonitoringEventInformationIeData const &data)
{
    if (!(buffer.writeUint32(data.scefReferenceId)))
    {
        errorStream.add((char *)"Encoding of scefReferenceId failed\n");
        return false;
    }
    if (!(buffer.writeUint8(data.scefIdLength)))
    {
        errorStream.add((char *)"Encoding of scefIdLength failed\n");
        return false;
    }
    if (!(buffer.writeUint8(data.scefId)))
    {
        errorStream.add((char *)"Encoding of scefId failed\n");
        return false;
    }

    return true;
}

bool MonitoringEventInformationIe::decodeMonitoringEventInformationIe(MsgBuffer &buffer, MonitoringEventInformationIeData &data, Uint16 length)
{     
    // TODO optimize the length checks
    
    Uint16 ieBoundary = buffer.getCurrentIndex() + length;

    buffer.readUint32(data.scefReferenceId);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: scefReferenceId\n");
        return false;
    }

    buffer.readUint8(data.scefIdLength);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: scefIdLength\n");
        return false;
    }

    buffer.readUint8(data.scefId);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: scefId\n");
        return false;
    }

    // The IE is decoded now. The buffer index should be pointing to the 
    // IE Boundary. If not, we have some more data left for the IE which we don't know
    // how to decode
    if (ieBoundary == buffer.getCurrentIndex())
    {
        return true;
    }
    else
    {
        errorStream.add((char *)"Unable to decode IE MonitoringEventInformationIe\n");
        return false;
    }
}
void MonitoringEventInformationIe::displayMonitoringEventInformationIe_v(MonitoringEventInformationIeData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"MonitoringEventInformationIeData:");
    stream.incrIndent();
    stream.endOfLine();
  
    stream.add((char *)"scefReferenceId: ");
    stream.add(data.scefReferenceId);
    stream.endOfLine();
  
    stream.add((char *)"scefIdLength: ");
    stream.add(data.scefIdLength);
    stream.endOfLine();
  
    stream.add((char *)"scefId: ");
    stream.add(data.scefId);
    stream.endOfLine();
    stream.decrIndent();
    stream.decrIndent();
}
