/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef MONITORINGEVENTINFORMATIONIE_H_
#define MONITORINGEVENTINFORMATIONIE_H_

#include "manual/gtpV2Ie.h"



class MonitoringEventInformationIe: public GtpV2Ie {
public:
    MonitoringEventInformationIe();
    virtual ~MonitoringEventInformationIe();

    bool encodeMonitoringEventInformationIe(MsgBuffer &buffer,
                 MonitoringEventInformationIeData const &data);
    bool decodeMonitoringEventInformationIe(MsgBuffer &buffer,
                 MonitoringEventInformationIeData &data, Uint16 length);
    void displayMonitoringEventInformationIe_v(MonitoringEventInformationIeData const &data,
                 Debug &stream);
};

#endif /* MONITORINGEVENTINFORMATIONIE_H_ */
