/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef NODENUMBERIE_H_
#define NODENUMBERIE_H_

#include "manual/gtpV2Ie.h"



class NodeNumberIe: public GtpV2Ie {
public:
    NodeNumberIe();
    virtual ~NodeNumberIe();

    bool encodeNodeNumberIe(MsgBuffer &buffer,
                 NodeNumberIeData const &data);
    bool decodeNodeNumberIe(MsgBuffer &buffer,
                 NodeNumberIeData &data, Uint16 length);
    void displayNodeNumberIe_v(NodeNumberIeData const &data,
                 Debug &stream);
};

#endif /* NODENUMBERIE_H_ */
