/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef PACKETFLOWIDIE_H_
#define PACKETFLOWIDIE_H_

#include "manual/gtpV2Ie.h"



class PacketFlowIdIe: public GtpV2Ie {
public:
    PacketFlowIdIe();
    virtual ~PacketFlowIdIe();

    bool encodePacketFlowIdIe(MsgBuffer &buffer,
                 PacketFlowIdIeData const &data);
    bool decodePacketFlowIdIe(MsgBuffer &buffer,
                 PacketFlowIdIeData &data, Uint16 length);
    void displayPacketFlowIdIe_v(PacketFlowIdIeData const &data,
                 Debug &stream);
};

#endif /* PACKETFLOWIDIE_H_ */
