/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */ 

/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/grpietemplate.cpp.tt>
 ******************************************************************************/
#include "pdnConnectionIe.h"
#include "gtpV2GrpIeDataTypes.h"
#include "manual/gtpV2GroupedIe.h"

#include "mmeSgsnUeScefPdnConnectionsInForwardRelocationRequest.h"
#include "mmeSgsnAmfUeEpsPdnConnectionsInForwardRelocationRequest.h"
#include "mmeSgsnAmfUeEpsPdnConnectionsInContextResponse.h"

PdnConnectionIe::PdnConnectionIe()
{
    ieType = PdnConnectionIeType;
   
    MmeSgsnUeScefPdnConnectionsInForwardRelocationRequest* mmeSgsnUeScefPdnConnectionsInForwardRelocationRequest_p = new (MmeSgsnUeScefPdnConnectionsInForwardRelocationRequest);
    insertGroupedIeObject(ForwardRelocationRequestMsgType, 0, mmeSgsnUeScefPdnConnectionsInForwardRelocationRequest_p);
    MmeSgsnAmfUeEpsPdnConnectionsInForwardRelocationRequest* mmeSgsnAmfUeEpsPdnConnectionsInForwardRelocationRequest_p = new (MmeSgsnAmfUeEpsPdnConnectionsInForwardRelocationRequest);
    insertGroupedIeObject(ForwardRelocationRequestMsgType, 0, mmeSgsnAmfUeEpsPdnConnectionsInForwardRelocationRequest_p);
    MmeSgsnAmfUeEpsPdnConnectionsInContextResponse* mmeSgsnAmfUeEpsPdnConnectionsInContextResponse_p = new (MmeSgsnAmfUeEpsPdnConnectionsInContextResponse);
    insertGroupedIeObject(ContextResponseMsgType, 0, mmeSgsnAmfUeEpsPdnConnectionsInContextResponse_p);
}

PdnConnectionIe::~PdnConnectionIe() {
// TODO Auto-generated destructor stub
}

GtpV2GroupedIe& PdnConnectionIe::getGroupedIe(Uint8 msgType, Uint8 instance)
{
    std::map<Uint16, GtpV2GroupedIe*>::iterator it;
    Uint16 key = msgType;
    key = (key << 8) + instance;
    it = groupedIeObjectContainer.find(key);
    return *(it->second);
}

void PdnConnectionIe::insertGroupedIeObject(Uint8 msgType, Uint8 instance, GtpV2GroupedIe* grpIe_p)
{

    Uint16 key = msgType;
    key = (key << 8) + instance;

    groupedIeObjectContainer.insert(std::pair<Uint16, GtpV2GroupedIe*>(key, grpIe_p));

}  