/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef PTMSISIGNATUREIE_H_
#define PTMSISIGNATUREIE_H_

#include "manual/gtpV2Ie.h"



class PTmsiSignatureIe: public GtpV2Ie {
public:
    PTmsiSignatureIe();
    virtual ~PTmsiSignatureIe();

    bool encodePTmsiSignatureIe(MsgBuffer &buffer,
                 PTmsiSignatureIeData const &data);
    bool decodePTmsiSignatureIe(MsgBuffer &buffer,
                 PTmsiSignatureIeData &data, Uint16 length);
    void displayPTmsiSignatureIe_v(PTmsiSignatureIeData const &data,
                 Debug &stream);
};

#endif /* PTMSISIGNATUREIE_H_ */
