/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.cpp.tt>
 ******************************************************************************/

#include "pTmsiIe.h"
#include "dataTypeCodecUtils.h"

PTmsiIe::PTmsiIe() 
{
    ieType = 111;
    // TODO

}

PTmsiIe::~PTmsiIe() {
    // TODO Auto-generated destructor stub
}

bool PTmsiIe::encodePTmsiIe(MsgBuffer &buffer, PTmsiIeData const &data)
{
    if (!(buffer.writeUint8(data.pTmsi)))
    {
        errorStream.add((char *)"Encoding of pTmsi failed\n");
        return false;
    }

    return true;
}

bool PTmsiIe::decodePTmsiIe(MsgBuffer &buffer, PTmsiIeData &data, Uint16 length)
{     
    // TODO optimize the length checks
    
    Uint16 ieBoundary = buffer.getCurrentIndex() + length;

    buffer.readUint8(data.pTmsi);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: pTmsi\n");
        return false;
    }

    // The IE is decoded now. The buffer index should be pointing to the 
    // IE Boundary. If not, we have some more data left for the IE which we don't know
    // how to decode
    if (ieBoundary == buffer.getCurrentIndex())
    {
        return true;
    }
    else
    {
        errorStream.add((char *)"Unable to decode IE PTmsiIe\n");
        return false;
    }
}
void PTmsiIe::displayPTmsiIe_v(PTmsiIeData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"PTmsiIeData:");
    stream.incrIndent();
    stream.endOfLine();
  
    stream.add((char *)"pTmsi: ");
    stream.add(data.pTmsi);
    stream.endOfLine();
    stream.decrIndent();
    stream.decrIndent();
}
