/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef PTMSIIE_H_
#define PTMSIIE_H_

#include "manual/gtpV2Ie.h"



class PTmsiIe: public GtpV2Ie {
public:
    PTmsiIe();
    virtual ~PTmsiIe();

    bool encodePTmsiIe(MsgBuffer &buffer,
                 PTmsiIeData const &data);
    bool decodePTmsiIe(MsgBuffer &buffer,
                 PTmsiIeData &data, Uint16 length);
    void displayPTmsiIe_v(PTmsiIeData const &data,
                 Debug &stream);
};

#endif /* PTMSIIE_H_ */
