/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.cpp.tt>
 ******************************************************************************/

#include "sourceIdentificationIe.h"
#include "dataTypeCodecUtils.h"

SourceIdentificationIe::SourceIdentificationIe() 
{
    ieType = 129;
    // TODO

}

SourceIdentificationIe::~SourceIdentificationIe() {
    // TODO Auto-generated destructor stub
}

bool SourceIdentificationIe::encodeSourceIdentificationIe(MsgBuffer &buffer, SourceIdentificationIeData const &data)
{
    if (!(buffer.writeUint64(data.targetCellID)))
    {
        errorStream.add((char *)"Encoding of targetCellID failed\n");
        return false;
    }
    if (!(buffer.writeUint8(data.sourceType)))
    {
        errorStream.add((char *)"Encoding of sourceType failed\n");
        return false;
    }
    if (!(buffer.writeUint8(data.sourceID)))
    {
        errorStream.add((char *)"Encoding of sourceID failed\n");
        return false;
    }

    return true;
}

bool SourceIdentificationIe::decodeSourceIdentificationIe(MsgBuffer &buffer, SourceIdentificationIeData &data, Uint16 length)
{     
    // TODO optimize the length checks
    
    Uint16 ieBoundary = buffer.getCurrentIndex() + length;

    buffer.readUint64(data.targetCellID);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: targetCellID\n");
        return false;
    }

    buffer.readUint8(data.sourceType);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: sourceType\n");
        return false;
    }

    buffer.readUint8(data.sourceID);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: sourceID\n");
        return false;
    }

    // The IE is decoded now. The buffer index should be pointing to the 
    // IE Boundary. If not, we have some more data left for the IE which we don't know
    // how to decode
    if (ieBoundary == buffer.getCurrentIndex())
    {
        return true;
    }
    else
    {
        errorStream.add((char *)"Unable to decode IE SourceIdentificationIe\n");
        return false;
    }
}
void SourceIdentificationIe::displaySourceIdentificationIe_v(SourceIdentificationIeData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"SourceIdentificationIeData:");
    stream.incrIndent();
    stream.endOfLine();
  
    stream.add((char *)"targetCellID: ");
    stream.add(data.targetCellID);
    stream.endOfLine();
  
    stream.add((char *)"sourceType: ");
    stream.add(data.sourceType);
    stream.endOfLine();
  
    stream.add((char *)"sourceID: ");
    stream.add(data.sourceID);
    stream.endOfLine();
    stream.decrIndent();
    stream.decrIndent();
}
