/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef SRVCCCAUSEIE_H_
#define SRVCCCAUSEIE_H_

#include "manual/gtpV2Ie.h"



class SrvccCauseIe: public GtpV2Ie {
public:
    SrvccCauseIe();
    virtual ~SrvccCauseIe();

    bool encodeSrvccCauseIe(MsgBuffer &buffer,
                 SrvccCauseIeData const &data);
    bool decodeSrvccCauseIe(MsgBuffer &buffer,
                 SrvccCauseIeData &data, Uint16 length);
    void displaySrvccCauseIe_v(SrvccCauseIeData const &data,
                 Debug &stream);
};

#endif /* SRVCCCAUSEIE_H_ */
