/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.cpp.tt>
 ******************************************************************************/

#include "srvccCauseIe.h"
#include "dataTypeCodecUtils.h"

SrvccCauseIe::SrvccCauseIe() 
{
    ieType = 56;
    // TODO

}

SrvccCauseIe::~SrvccCauseIe() {
    // TODO Auto-generated destructor stub
}

bool SrvccCauseIe::encodeSrvccCauseIe(MsgBuffer &buffer, SrvccCauseIeData const &data)
{
    if (!(buffer.writeUint8(data.srvccCauseValue)))
    {
        errorStream.add((char *)"Encoding of srvccCauseValue failed\n");
        return false;
    }

    return true;
}

bool SrvccCauseIe::decodeSrvccCauseIe(MsgBuffer &buffer, SrvccCauseIeData &data, Uint16 length)
{     
    // TODO optimize the length checks
    
    Uint16 ieBoundary = buffer.getCurrentIndex() + length;

    buffer.readUint8(data.srvccCauseValue);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: srvccCauseValue\n");
        return false;
    }

    // The IE is decoded now. The buffer index should be pointing to the 
    // IE Boundary. If not, we have some more data left for the IE which we don't know
    // how to decode
    if (ieBoundary == buffer.getCurrentIndex())
    {
        return true;
    }
    else
    {
        errorStream.add((char *)"Unable to decode IE SrvccCauseIe\n");
        return false;
    }
}
void SrvccCauseIe::displaySrvccCauseIe_v(SrvccCauseIeData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"SrvccCauseIeData:");
    stream.incrIndent();
    stream.endOfLine();
  
    stream.add((char *)"srvccCauseValue: ");
    stream.add(data.srvccCauseValue);
    stream.endOfLine();
    stream.decrIndent();
    stream.decrIndent();
}
