/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef STNSRIE_H_
#define STNSRIE_H_

#include "manual/gtpV2Ie.h"



class StnSrIe: public GtpV2Ie {
public:
    StnSrIe();
    virtual ~StnSrIe();

    bool encodeStnSrIe(MsgBuffer &buffer,
                 StnSrIeData const &data);
    bool decodeStnSrIe(MsgBuffer &buffer,
                 StnSrIeData &data, Uint16 length);
    void displayStnSrIe_v(StnSrIeData const &data,
                 Debug &stream);
};

#endif /* STNSRIE_H_ */
