/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.cpp.tt>
 ******************************************************************************/

#include "stnSrIe.h"
#include "dataTypeCodecUtils.h"

StnSrIe::StnSrIe() 
{
    ieType = 51;
    // TODO

}

StnSrIe::~StnSrIe() {
    // TODO Auto-generated destructor stub
}

bool StnSrIe::encodeStnSrIe(MsgBuffer &buffer, StnSrIeData const &data)
{
    if (!(buffer.writeUint8(data.NANPI)))
    {
        errorStream.add((char *)"Encoding of NANPI failed\n");
        return false;
    }
    if(!(buffer.writeBits(data.Digit2, 4)))
    {
        errorStream.add((char *)"Encoding of Digit2 failed\n");
        return false;
    }
    if(!(buffer.writeBits(data.Digit1, 4)))
    {
        errorStream.add((char *)"Encoding of Digit1 failed\n");
        return false;
    }

    return true;
}

bool StnSrIe::decodeStnSrIe(MsgBuffer &buffer, StnSrIeData &data, Uint16 length)
{     
    // TODO optimize the length checks
    
    Uint16 ieBoundary = buffer.getCurrentIndex() + length;

    buffer.readUint8(data.NANPI);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: NANPI\n");
        return false;
    }
    data.Digit2 = buffer.readBits(4);
    // confirm that we are not reading beyond the IE boundary
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: Digit2\n");
        return false;
    }
    data.Digit1 = buffer.readBits(4);
    // confirm that we are not reading beyond the IE boundary
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: Digit1\n");
        return false;
    }

    // The IE is decoded now. The buffer index should be pointing to the 
    // IE Boundary. If not, we have some more data left for the IE which we don't know
    // how to decode
    if (ieBoundary == buffer.getCurrentIndex())
    {
        return true;
    }
    else
    {
        errorStream.add((char *)"Unable to decode IE StnSrIe\n");
        return false;
    }
}
void StnSrIe::displayStnSrIe_v(StnSrIeData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"StnSrIeData:");
    stream.incrIndent();
    stream.endOfLine();
  
    stream.add((char *)"NANPI: ");
    stream.add(data.NANPI);
    stream.endOfLine();
  
    stream.add( (char *)"Digit2: "); 
    stream.add((Uint8)data.Digit2);
    stream.endOfLine();
  
    stream.add( (char *)"Digit1: "); 
    stream.add((Uint8)data.Digit1);
    stream.endOfLine();
    stream.decrIndent();
    stream.decrIndent();
}
