/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef SVFLAGSIE_H_
#define SVFLAGSIE_H_

#include "manual/gtpV2Ie.h"



class SvFlagsIe: public GtpV2Ie {
public:
    SvFlagsIe();
    virtual ~SvFlagsIe();

    bool encodeSvFlagsIe(MsgBuffer &buffer,
                 SvFlagsIeData const &data);
    bool decodeSvFlagsIe(MsgBuffer &buffer,
                 SvFlagsIeData &data, Uint16 length);
    void displaySvFlagsIe_v(SvFlagsIeData const &data,
                 Debug &stream);
};

#endif /* SVFLAGSIE_H_ */
