/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.cpp.tt>
 ******************************************************************************/

#include "targetRncIdIe.h"
#include "dataTypeCodecUtils.h"

TargetRncIdIe::TargetRncIdIe() 
{
    ieType = 57;
    // TODO

}

TargetRncIdIe::~TargetRncIdIe() {
    // TODO Auto-generated destructor stub
}

bool TargetRncIdIe::encodeTargetRncIdIe(MsgBuffer &buffer, TargetRncIdIeData const &data)
{
    if (!(buffer.writeUint8(data.RncID)))
    {
        errorStream.add((char *)"Encoding of RncID failed\n");
        return false;
    }

    return true;
}

bool TargetRncIdIe::decodeTargetRncIdIe(MsgBuffer &buffer, TargetRncIdIeData &data, Uint16 length)
{     
    // TODO optimize the length checks
    
    Uint16 ieBoundary = buffer.getCurrentIndex() + length;

    buffer.readUint8(data.RncID);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: RncID\n");
        return false;
    }

    // The IE is decoded now. The buffer index should be pointing to the 
    // IE Boundary. If not, we have some more data left for the IE which we don't know
    // how to decode
    if (ieBoundary == buffer.getCurrentIndex())
    {
        return true;
    }
    else
    {
        errorStream.add((char *)"Unable to decode IE TargetRncIdIe\n");
        return false;
    }
}
void TargetRncIdIe::displayTargetRncIdIe_v(TargetRncIdIeData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"TargetRncIdIeData:");
    stream.incrIndent();
    stream.endOfLine();
  
    stream.add((char *)"RncID: ");
    stream.add(data.RncID);
    stream.endOfLine();
    stream.decrIndent();
    stream.decrIndent();
}
