/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.cpp.tt>
 ******************************************************************************/

#include "targetToSourceTransparentContainerIe.h"
#include "dataTypeCodecUtils.h"

TargetToSourceTransparentContainerIe::TargetToSourceTransparentContainerIe() 
{
    ieType = 53;
    // TODO

}

TargetToSourceTransparentContainerIe::~TargetToSourceTransparentContainerIe() {
    // TODO Auto-generated destructor stub
}

bool TargetToSourceTransparentContainerIe::encodeTargetToSourceTransparentContainerIe(MsgBuffer &buffer, TargetToSourceTransparentContainerIeData const &data)
{
    if (!(buffer.writeUint8(data.lengthOfTheTransparentcontainer)))
    {
        errorStream.add((char *)"Encoding of lengthOfTheTransparentcontainer failed\n");
        return false;
    }
    if (!(buffer.writeUint8(data.transparentContainer)))
    {
        errorStream.add((char *)"Encoding of transparentContainer failed\n");
        return false;
    }

    return true;
}

bool TargetToSourceTransparentContainerIe::decodeTargetToSourceTransparentContainerIe(MsgBuffer &buffer, TargetToSourceTransparentContainerIeData &data, Uint16 length)
{     
    // TODO optimize the length checks
    
    Uint16 ieBoundary = buffer.getCurrentIndex() + length;

    buffer.readUint8(data.lengthOfTheTransparentcontainer);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: lengthOfTheTransparentcontainer\n");
        return false;
    }

    buffer.readUint8(data.transparentContainer);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: transparentContainer\n");
        return false;
    }

    // The IE is decoded now. The buffer index should be pointing to the 
    // IE Boundary. If not, we have some more data left for the IE which we don't know
    // how to decode
    if (ieBoundary == buffer.getCurrentIndex())
    {
        return true;
    }
    else
    {
        errorStream.add((char *)"Unable to decode IE TargetToSourceTransparentContainerIe\n");
        return false;
    }
}
void TargetToSourceTransparentContainerIe::displayTargetToSourceTransparentContainerIe_v(TargetToSourceTransparentContainerIeData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"TargetToSourceTransparentContainerIeData:");
    stream.incrIndent();
    stream.endOfLine();
  
    stream.add((char *)"lengthOfTheTransparentcontainer: ");
    stream.add(data.lengthOfTheTransparentcontainer);
    stream.endOfLine();
  
    stream.add((char *)"transparentContainer: ");
    stream.add(data.transparentContainer);
    stream.endOfLine();
    stream.decrIndent();
    stream.decrIndent();
}
