/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef TARGETTOSOURCETRANSPARENTCONTAINERIE_H_
#define TARGETTOSOURCETRANSPARENTCONTAINERIE_H_

#include "manual/gtpV2Ie.h"



class TargetToSourceTransparentContainerIe: public GtpV2Ie {
public:
    TargetToSourceTransparentContainerIe();
    virtual ~TargetToSourceTransparentContainerIe();

    bool encodeTargetToSourceTransparentContainerIe(MsgBuffer &buffer,
                 TargetToSourceTransparentContainerIeData const &data);
    bool decodeTargetToSourceTransparentContainerIe(MsgBuffer &buffer,
                 TargetToSourceTransparentContainerIeData &data, Uint16 length);
    void displayTargetToSourceTransparentContainerIe_v(TargetToSourceTransparentContainerIeData const &data,
                 Debug &stream);
};

#endif /* TARGETTOSOURCETRANSPARENTCONTAINERIE_H_ */
