/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef TEIDCIE_H_
#define TEIDCIE_H_

#include "manual/gtpV2Ie.h"



class TeidCIe: public GtpV2Ie {
public:
    TeidCIe();
    virtual ~TeidCIe();

    bool encodeTeidCIe(MsgBuffer &buffer,
                 TeidCIeData const &data);
    bool decodeTeidCIe(MsgBuffer &buffer,
                 TeidCIeData &data, Uint16 length);
    void displayTeidCIe_v(TeidCIeData const &data,
                 Debug &stream);
};

#endif /* TEIDCIE_H_ */
