/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef TIIE_H_
#define TIIE_H_

#include "manual/gtpV2Ie.h"



class TiIe: public GtpV2Ie {
public:
    TiIe();
    virtual ~TiIe();

    bool encodeTiIe(MsgBuffer &buffer,
                 TiIeData const &data);
    bool decodeTiIe(MsgBuffer &buffer,
                 TiIeData &data, Uint16 length);
    void displayTiIe_v(TiIeData const &data,
                 Debug &stream);
};

#endif /* TIIE_H_ */
