/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.cpp.tt>
 ******************************************************************************/

#include "wlanOffloadabilityIndicationIe.h"
#include "dataTypeCodecUtils.h"

WlanOffloadabilityIndicationIe::WlanOffloadabilityIndicationIe() 
{
    ieType = 185;
    // TODO

}

WlanOffloadabilityIndicationIe::~WlanOffloadabilityIndicationIe() {
    // TODO Auto-generated destructor stub
}

bool WlanOffloadabilityIndicationIe::encodeWlanOffloadabilityIndicationIe(MsgBuffer &buffer, WlanOffloadabilityIndicationIeData const &data)
{
    buffer.skipBits(6);

    if(!(buffer.writeBits(data.eutranIndication, 1)))
    {
        errorStream.add((char *)"Encoding of eutranIndication failed\n");
        return false;
    }
    if(!(buffer.writeBits(data.utranIndication, 1)))
    {
        errorStream.add((char *)"Encoding of utranIndication failed\n");
        return false;
    }

    return true;
}

bool WlanOffloadabilityIndicationIe::decodeWlanOffloadabilityIndicationIe(MsgBuffer &buffer, WlanOffloadabilityIndicationIeData &data, Uint16 length)
{     
    // TODO optimize the length checks
    
    Uint16 ieBoundary = buffer.getCurrentIndex() + length;
    buffer.skipBits(6);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: \n");
        return false;
    }

    data.eutranIndication = buffer.readBits(1);
    // confirm that we are not reading beyond the IE boundary
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: eutranIndication\n");
        return false;
    }
    data.utranIndication = buffer.readBits(1);
    // confirm that we are not reading beyond the IE boundary
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: utranIndication\n");
        return false;
    }

    // The IE is decoded now. The buffer index should be pointing to the 
    // IE Boundary. If not, we have some more data left for the IE which we don't know
    // how to decode
    if (ieBoundary == buffer.getCurrentIndex())
    {
        return true;
    }
    else
    {
        errorStream.add((char *)"Unable to decode IE WlanOffloadabilityIndicationIe\n");
        return false;
    }
}
void WlanOffloadabilityIndicationIe::displayWlanOffloadabilityIndicationIe_v(WlanOffloadabilityIndicationIeData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"WlanOffloadabilityIndicationIeData:");
    stream.incrIndent();
    stream.endOfLine();
  
    stream.add( (char *)"eutranIndication: "); 
    stream.add((Uint8)data.eutranIndication);
    stream.endOfLine();
  
    stream.add( (char *)"utranIndication: "); 
    stream.add((Uint8)data.utranIndication);
    stream.endOfLine();
    stream.decrIndent();
    stream.decrIndent();
}
