 /*
 * Copyright 2021-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */ 
/******************************************************************************
 * srvccProcedureContextManager.cpp
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/ctxtManagerTmpls/blockPoolManager.cpp.tt>
 ******************************************************************************/

#include "memPoolManager.h"
#include "contextManager/dataBlocks.h"
#include "contextManager/srvccProcedureContextManager.h"

using namespace cmn::memPool;

namespace mme
{
	/******************************************************************************
	* Constructor
	******************************************************************************/
	SrvccProcedureContextManager::SrvccProcedureContextManager(int numOfBlocks):poolManager_m(numOfBlocks)
	{
	}
	
	/******************************************************************************
	* Destructor
	******************************************************************************/
	SrvccProcedureContextManager::~SrvccProcedureContextManager()
	{
	}
	
	/******************************************************************************
	* Allocate SrvccProcedureContext data block
	******************************************************************************/
	SrvccProcedureContext* SrvccProcedureContextManager::allocateSrvccProcedureContext()
	{
		SrvccProcedureContext* SrvccProcedureContext_p = poolManager_m.allocate();
		return SrvccProcedureContext_p;
	}
	
	/******************************************************************************
	* Deallocate a SrvccProcedureContext data block
	******************************************************************************/
	void SrvccProcedureContextManager::deallocateSrvccProcedureContext(SrvccProcedureContext* SrvccProcedureContextp )
	{
		poolManager_m.free( SrvccProcedureContextp );
	}
}