/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/msgtemplate.cpp.tt>
 ******************************************************************************/ 

#include "srvccPsToCsResponseMsg.h"
#include "../ieClasses/manual/gtpV2Ie.h"
#include "../ieClasses/gtpV2IeFactory.h"
#include "../ieClasses/causeIe.h"
#include "../ieClasses/ipAddressIe.h"
#include "../ieClasses/teidCIe.h"
#include "../ieClasses/targetToSourceTransparentContainerIe.h"

SrvccPsToCsResponseMsg::SrvccPsToCsResponseMsg()
{
    msgType = SrvccPsToCsResponseMsgType;
    Uint16 mandIe;
    mandIe = CauseIeType;
    mandIe = (mandIe << 8) | 0; // cause
    mandatoryIeSet.insert(mandIe);
}

SrvccPsToCsResponseMsg::~SrvccPsToCsResponseMsg()
{

}

bool SrvccPsToCsResponseMsg::encodeSrvccPsToCsResponseMsg(MsgBuffer &buffer,
                        SrvccPsToCsResponseMsgData
							const &data)
{
    bool rc = false;
    GtpV2IeHeader header;
    Uint16 startIndex = 0;
    Uint16 endIndex = 0;
    Uint16 length = 0;

    
    // Encode the Ie Header
    header.ieType = CauseIeType;
    header.instance = 0;
    header.length = 0; // We will encode the IE first and then update the length
    GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
    startIndex = buffer.getCurrentIndex(); 
    CauseIe cause=
    dynamic_cast<
    CauseIe&>(GtpV2IeFactory::getInstance().getIeObject(CauseIeType));
    rc = cause.encodeCauseIe(buffer, data.cause);
    endIndex = buffer.getCurrentIndex();
    length = endIndex - startIndex;
    
    // encode the length value now
    buffer.goToIndex(startIndex - 3);
    buffer.writeUint16(length, false);
    buffer.goToIndex(endIndex);

    if (!(rc))
    { 
        errorStream.add((char *)"Failed to encode IE: cause\n");
        return false;
    }

    if (data.mscServerSvAddressForControlPlaneIePresent)
    {
        
        // Encode the Ie Header
        header.ieType = IpAddressIeType;
        header.instance = 0;
        header.length = 0; // We will encode the IE first and then update the length
        GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
        startIndex = buffer.getCurrentIndex(); 
        IpAddressIe mscServerSvAddressForControlPlane=
        dynamic_cast<
        IpAddressIe&>(GtpV2IeFactory::getInstance().getIeObject(IpAddressIeType));
        rc = mscServerSvAddressForControlPlane.encodeIpAddressIe(buffer, data.mscServerSvAddressForControlPlane);
        endIndex = buffer.getCurrentIndex();
        length = endIndex - startIndex;
        
        // encode the length value now
        buffer.goToIndex(startIndex - 3);
        buffer.writeUint16(length, false);
        buffer.goToIndex(endIndex);

        if (!(rc))
        { 
            errorStream.add((char *)"Failed to encode IE: mscServerSvAddressForControlPlane\n");
            return false;
        }
    }

    if (data.mscServerSvTeidForControlPlaneIePresent)
    {
        
        // Encode the Ie Header
        header.ieType = TeidCIeType;
        header.instance = 0;
        header.length = 0; // We will encode the IE first and then update the length
        GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
        startIndex = buffer.getCurrentIndex(); 
        TeidCIe mscServerSvTeidForControlPlane=
        dynamic_cast<
        TeidCIe&>(GtpV2IeFactory::getInstance().getIeObject(TeidCIeType));
        rc = mscServerSvTeidForControlPlane.encodeTeidCIe(buffer, data.mscServerSvTeidForControlPlane);
        endIndex = buffer.getCurrentIndex();
        length = endIndex - startIndex;
        
        // encode the length value now
        buffer.goToIndex(startIndex - 3);
        buffer.writeUint16(length, false);
        buffer.goToIndex(endIndex);

        if (!(rc))
        { 
            errorStream.add((char *)"Failed to encode IE: mscServerSvTeidForControlPlane\n");
            return false;
        }
    }

    if (data.targetToSourceTransparentContainerIePresent)
    {
        
        // Encode the Ie Header
        header.ieType = TargetToSourceTransparentContainerIeType;
        header.instance = 0;
        header.length = 0; // We will encode the IE first and then update the length
        GtpV2Ie::encodeGtpV2IeHeader(buffer, header);
        startIndex = buffer.getCurrentIndex(); 
        TargetToSourceTransparentContainerIe targetToSourceTransparentContainer=
        dynamic_cast<
        TargetToSourceTransparentContainerIe&>(GtpV2IeFactory::getInstance().getIeObject(TargetToSourceTransparentContainerIeType));
        rc = targetToSourceTransparentContainer.encodeTargetToSourceTransparentContainerIe(buffer, data.targetToSourceTransparentContainer);
        endIndex = buffer.getCurrentIndex();
        length = endIndex - startIndex;
        
        // encode the length value now
        buffer.goToIndex(startIndex - 3);
        buffer.writeUint16(length, false);
        buffer.goToIndex(endIndex);

        if (!(rc))
        { 
            errorStream.add((char *)"Failed to encode IE: targetToSourceTransparentContainer\n");
            return false;
        }
    }
    return rc;

}

bool SrvccPsToCsResponseMsg::decodeSrvccPsToCsResponseMsg(MsgBuffer &buffer,
 SrvccPsToCsResponseMsgData 
 &data, Uint16 length)
{

    bool rc = false;
    GtpV2IeHeader ieHeader;
  
    set<Uint16> mandatoryIeLocalList = mandatoryIeSet;
    while (buffer.lengthLeft() > IE_HEADER_SIZE)
    {
        GtpV2Ie::decodeGtpV2IeHeader(buffer, ieHeader);
        if (ieHeader.length > buffer.lengthLeft())
        {
            // We do not have enough bytes left in the message for this IE
            errorStream.add((char *)"IE Length exceeds beyond message boundary\n");
            errorStream.add((char *)"  Offending IE Type: ");
            errorStream.add(ieHeader.ieType);
            errorStream.add((char *)"\n  Ie Length in Header: ");
            errorStream.add(ieHeader.length);
            errorStream.add((char *)"\n  Bytes left in message: ");
            errorStream.add(buffer.lengthLeft());
            errorStream.endOfLine();
            return false;
        }

        switch (ieHeader.ieType){
     
            case CauseIeType:
            {
                CauseIe ieObject =
                dynamic_cast<
                CauseIe&>(GtpV2IeFactory::getInstance().getIeObject(CauseIeType));

                if(ieHeader.instance == 0)
                {
                    rc = ieObject.decodeCauseIe(buffer, data.cause, ieHeader.length);

                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: cause\n");
                        return false;
                    }
                }

                else
                {
                    // Unknown IE instance print error
                    errorStream.add((char *)"Unknown IE Type: ");
                    errorStream.add(ieHeader.ieType);
                    errorStream.endOfLine();
                    buffer.skipBytes(ieHeader.length);
                }
                break;
            }
     
            case IpAddressIeType:
            {
                IpAddressIe ieObject =
                dynamic_cast<
                IpAddressIe&>(GtpV2IeFactory::getInstance().getIeObject(IpAddressIeType));

                if(ieHeader.instance == 0)
                {
                    rc = ieObject.decodeIpAddressIe(buffer, data.mscServerSvAddressForControlPlane, ieHeader.length);

                    data.mscServerSvAddressForControlPlaneIePresent = true;
                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: mscServerSvAddressForControlPlane\n");
                        return false;
                    }
                }

                else
                {
                    // Unknown IE instance print error
                    errorStream.add((char *)"Unknown IE Type: ");
                    errorStream.add(ieHeader.ieType);
                    errorStream.endOfLine();
                    buffer.skipBytes(ieHeader.length);
                }
                break;
            }
     
            case TeidCIeType:
            {
                TeidCIe ieObject =
                dynamic_cast<
                TeidCIe&>(GtpV2IeFactory::getInstance().getIeObject(TeidCIeType));

                if(ieHeader.instance == 0)
                {
                    rc = ieObject.decodeTeidCIe(buffer, data.mscServerSvTeidForControlPlane, ieHeader.length);

                    data.mscServerSvTeidForControlPlaneIePresent = true;
                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: mscServerSvTeidForControlPlane\n");
                        return false;
                    }
                }

                else
                {
                    // Unknown IE instance print error
                    errorStream.add((char *)"Unknown IE Type: ");
                    errorStream.add(ieHeader.ieType);
                    errorStream.endOfLine();
                    buffer.skipBytes(ieHeader.length);
                }
                break;
            }
     
            case TargetToSourceTransparentContainerIeType:
            {
                TargetToSourceTransparentContainerIe ieObject =
                dynamic_cast<
                TargetToSourceTransparentContainerIe&>(GtpV2IeFactory::getInstance().getIeObject(TargetToSourceTransparentContainerIeType));

                if(ieHeader.instance == 0)
                {
                    rc = ieObject.decodeTargetToSourceTransparentContainerIe(buffer, data.targetToSourceTransparentContainer, ieHeader.length);

                    data.targetToSourceTransparentContainerIePresent = true;
                    if (!(rc))
                    {
                        errorStream.add((char *)"Failed to decode IE: targetToSourceTransparentContainer\n");
                        return false;
                    }
                }

                else
                {
                    // Unknown IE instance print error
                    errorStream.add((char *)"Unknown IE Type: ");
                    errorStream.add(ieHeader.ieType);
                    errorStream.endOfLine();
                    buffer.skipBytes(ieHeader.length);
                }
                break;
            }

            default:
            {
                // Unknown IE print error
                errorStream.add((char *)"Unknown IE Type: ");
                errorStream.add(ieHeader.ieType);
                errorStream.endOfLine();
                buffer.skipBytes(ieHeader.length);
            }
        }
    }
    return rc; // TODO validations
}

void SrvccPsToCsResponseMsg::
displaySrvccPsToCsResponseMsgData_v(SrvccPsToCsResponseMsgData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"SrvccPsToCsResponseMsg:");
    stream.endOfLine();
    stream.incrIndent();
        
    
    stream.add((char *)"IE - cause:");
    stream.endOfLine();
    CauseIe cause=
    dynamic_cast<
    CauseIe&>(GtpV2IeFactory::getInstance().getIeObject(CauseIeType));
    cause.displayCauseIe_v(data.cause, stream);

    if (data.mscServerSvAddressForControlPlaneIePresent)
    {


        stream.add((char *)"IE - mscServerSvAddressForControlPlane:");
        stream.endOfLine();
        IpAddressIe mscServerSvAddressForControlPlane=
        dynamic_cast<
        IpAddressIe&>(GtpV2IeFactory::getInstance().getIeObject(IpAddressIeType));
        mscServerSvAddressForControlPlane.displayIpAddressIe_v(data.mscServerSvAddressForControlPlane, stream);

    }
    if (data.mscServerSvTeidForControlPlaneIePresent)
    {


        stream.add((char *)"IE - mscServerSvTeidForControlPlane:");
        stream.endOfLine();
        TeidCIe mscServerSvTeidForControlPlane=
        dynamic_cast<
        TeidCIe&>(GtpV2IeFactory::getInstance().getIeObject(TeidCIeType));
        mscServerSvTeidForControlPlane.displayTeidCIe_v(data.mscServerSvTeidForControlPlane, stream);

    }
    if (data.targetToSourceTransparentContainerIePresent)
    {


        stream.add((char *)"IE - targetToSourceTransparentContainer:");
        stream.endOfLine();
        TargetToSourceTransparentContainerIe targetToSourceTransparentContainer=
        dynamic_cast<
        TargetToSourceTransparentContainerIe&>(GtpV2IeFactory::getInstance().getIeObject(TargetToSourceTransparentContainerIeType));
        targetToSourceTransparentContainer.displayTargetToSourceTransparentContainerIe_v(data.targetToSourceTransparentContainer, stream);

    }

    stream.decrIndent();
    stream.decrIndent();
}

