 /*
 * Copyright 2021-present, Infosys Limited.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef __SrvccProcedureContextManager__
#define __SrvccProcedureContextManager__
/******************************************************
* srvccProcedureContextManager.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/ctxtManagerTmpls/blockPoolManager.h.tt>
 ***************************************/
#include "memPoolManager.h"

namespace mme
{
	class SrvccProcedureContext;
	class SrvccProcedureContextManager
	{
		public:
			/****************************************
			* SrvccProcedureContextManager
			*  constructor
			****************************************/
			SrvccProcedureContextManager(int numOfBlocks);
			
			/****************************************
			* SrvccProcedureContextManager
			*    Destructor
			****************************************/
			~SrvccProcedureContextManager();
			
			/******************************************
			 * allocateSrvccProcedureContext
			 * allocate SrvccProcedureContext data block
			 ******************************************/
			SrvccProcedureContext* allocateSrvccProcedureContext();
			
			/******************************************
			 * deallocateSrvccProcedureContext
			 * deallocate a SrvccProcedureContext data block
			 ******************************************/
			void deallocateSrvccProcedureContext(SrvccProcedureContext* SrvccProcedureContextp );
	
		private:
			cmn::memPool::MemPoolManager<SrvccProcedureContext> poolManager_m;
	};
};

#endif
		
		
